// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXRS-T1iDEAxcmUaWIf62et4wQzbJS34c',
    appId: '1:565903466138:web:2e4708560e82d00f458923',
    messagingSenderId: '565903466138',
    projectId: 'cmdgroupproject-e5914',
    authDomain: 'cmdgroupproject-e5914.firebaseapp.com',
    storageBucket: 'cmdgroupproject-e5914.firebasestorage.app',
    measurementId: 'G-T0VRK9B772',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzghuMrmjypi4l7ZwS_iST1QVyu7ljDq8',
    appId: '1:565903466138:android:3ef8f64e7fbb7fa0458923',
    messagingSenderId: '565903466138',
    projectId: 'cmdgroupproject-e5914',
    storageBucket: 'cmdgroupproject-e5914.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWzrXW-JLKgu8t0eooBXsaTKpsoHdyfwU',
    appId: '1:565903466138:ios:4738b8aa77c1bc19458923',
    messagingSenderId: '565903466138',
    projectId: 'cmdgroupproject-e5914',
    storageBucket: 'cmdgroupproject-e5914.firebasestorage.app',
    iosBundleId: 'inti.edu.mobileApplicationGroup',
  );
}
