import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file is automatically generated by the CLI tool
import 'package:mobile_application_group/widget_tree.dart';

Future<void> main() async {
  // Run inside a guarded zone so uncaught async errors from plugins (e.g. the
  // pedometer throwing on devices without a step sensor) are logged instead of
  // surfacing as crash-style "Unhandled Exception" output.
  runZonedGuarded(() async {
    // Ensure Flutter bindings are ready before running async native code
    WidgetsFlutterBinding.ensureInitialized();

    // Initialize Firebase across Android/iOS
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );

    runApp(const MaterialApp(
      home: WidgetTree(),
    ));
  }, (error, stack) {
    debugPrint('Uncaught zone error: $error');
  });
}
