import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file is automatically generated by the CLI tool
import 'screens/login/login_register_page.dart';
import 'package:mobile_application_group/widget_tree.dart';

Future<void>  main() async {
  // Ensure Flutter bindings are ready before running async native code
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase across Android/iOS
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MaterialApp(
    home: const WidgetTree(),
  ));
}