import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:workmanager/workmanager.dart';
import 'firebase_options.dart'; // This file is automatically generated by the CLI tool
import 'package:mobile_application_group/widget_tree.dart';
import 'package:mobile_application_group/services/meal_planner.dart';

/// Unique name + task id for the weekly meal-plan background job.
const String kMealPlanTask = 'weeklyMealPlan';

/// Background entry point (runs in its own isolate). Kept top-level + annotated
/// so the engine can find it when Workmanager wakes the app.
@pragma('vm:entry-point')
void callbackDispatcher() {
  Workmanager().executeTask((task, inputData) async {
    try {
      // Runs offline-prep online: regenerate the week if stale, then
      // pre-schedule the offline meal notifications.
      await MealPlanner().runWeeklyPlan();
    } catch (e) {
      debugPrint('Meal-plan background task failed: $e');
    }
    return true;
  });
}

Future<void> main() async {
  // Run inside a guarded zone so uncaught async errors from plugins (e.g. the
  // pedometer throwing on devices without a step sensor) are logged instead of
  // surfacing as crash-style "Unhandled Exception" output.
  runZonedGuarded(() async {
    // Ensure Flutter bindings are ready before running async native code
    WidgetsFlutterBinding.ensureInitialized();

    // Initialize Firebase across Android/iOS
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );

    // Register the weekly meal-plan background job. A daily cadence with a
    // network constraint lets it re-plan opportunistically when online; the
    // job itself no-ops if the cached plan is still fresh.
    try {
      await Workmanager().initialize(callbackDispatcher);
      await Workmanager().registerPeriodicTask(
        'weekly-meal-plan',
        kMealPlanTask,
        frequency: const Duration(days: 1),
        constraints: Constraints(networkType: NetworkType.connected),
        existingWorkPolicy: ExistingPeriodicWorkPolicy.keep,
      );
    } catch (e) {
      debugPrint('Workmanager init failed: $e');
    }

    runApp(const MaterialApp(
      home: WidgetTree(),
    ));
  }, (error, stack) {
    debugPrint('Uncaught zone error: $error');
  });
}
